services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "zorin"
      USERNAME: "MASTER"
      PASSWORD: "admin@123"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
      DISK_SIZE: "400G"
      DISK2_SIZE: "100G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
